package cn.com.study.application.model;

public class UcRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.uid
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.zid
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    private String zid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.name
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.create_time
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.delete_flag
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.uid
     *
     * @return the value of uc_role.uid
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.uid
     *
     * @param uid the value for uc_role.uid
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.zid
     *
     * @return the value of uc_role.zid
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public String getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.zid
     *
     * @param zid the value for uc_role.zid
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public void setZid(String zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.name
     *
     * @return the value of uc_role.name
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.name
     *
     * @param name the value for uc_role.name
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.create_time
     *
     * @return the value of uc_role.create_time
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.create_time
     *
     * @param createTime the value for uc_role.create_time
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.delete_flag
     *
     * @return the value of uc_role.delete_flag
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.delete_flag
     *
     * @param deleteFlag the value for uc_role.delete_flag
     *
     * @mbggenerated Tue Apr 26 21:53:13 CST 2016
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}